CREATE TABLE CONFIGURACAO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GUID CHAR(36) NOT NULL,
    CHAVE_PUBLICA TEXT NOT NULL,
    CHAVE_PRIVADA TEXT NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EMPRESA_ID INT NOT NULL,

    CONSTRAINT FK_CONFIGURACAO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES PAYSAFE.EMPRESA (ID)
);
