CREATE TABLE EMPRESA (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GUID CHAR(36) NOT NULL,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    NOME_FANTASIA VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(18) NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    PLANO_ID INT NOT NULL,

    CONSTRAINT FK_EMPRESA_PLANO FOREIGN KEY (PLANO_ID) REFERENCES PLANO(ID)
);