CREATE TABLE GATEWAY (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GUID CHAR(36) NOT NULL,
    SERVICO INT NOT NULL,
    METODO_PAGAMENTO INT NOT NULL,
    PRIORIDADE INT NOT NULL,
    EMPRESA_ID INT NOT NULL,

    CONSTRAINT FK_GATEWAY_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES PAYSAFE.EMPRESA (ID)
);
