CREATE TABLE GATEWAY_PARAMETROS (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GUID CHAR(36) NOT NULL,
    CHAVE VARCHAR(255) NOT NULL,
    VALOR TEXT NOT NULL,
    GATEWAY_ID INT NOT NULL,

    CONSTRAINT FK_PARAMETROS_GATEWAY FOREIGN KEY (GATEWAY_ID) REFERENCES PAYSAFE.GATEWAY (ID)
);