CREATE TABLE PLANO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GUID CHAR(36) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    MENSALIDADE INT NOT NULL,
    VOLUME INT NOT NULL,
    VALOR_EXCEDENTE INT NOT NULL,
    MAXIMO_USUARIOS INT NOT NULL,
    MAXIMO_GRUPOS INT NOT NULL
);
