CREATE TABLE TRANSACAO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GUID CHAR(36) NOT NULL,
    PRECO_TOTAL INT NOT NULL,
    TAXA INT NOT NULL,
    FRETE INT NOT NULL,
    ITENS TEXT NOT NULL,
    STATUS INT NOT NULL,
    EMPRESA_ID INT NOT NULL,
    
    CONSTRAINT FK_TRANSACAO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES PAYSAFE.EMPRESA (ID)
);