CREATE TABLE TRANSACAO_PAGAMENTO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GUID CHAR(36) NOT NULL,
    METODO_PAGAMENTO INT,
    VALOR INT NOT NULL,
    STATUS_PAGAMENTO INT NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    TRANSACAO_ID INT NOT NULL,

    CONSTRAINT FK_TRANSACAO_PAGAMENTO_TRANSACAO FOREIGN KEY (TRANSACAO_ID) REFERENCES PAYSAFE.TRANSACAO (ID)
);