CREATE TABLE USUARIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GUID CHAR(36) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(255),
    TELEFONE VARCHAR(20),
    EXCLUIDO BOOLEAN,
    EMPRESA_ID INT NOT NULL,

    CONSTRAINT FK_USUARIO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);
